# Generated by Django 5.2.1 on 2025-05-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exercise', models.CharField(choices=[('pushups', 'Pompki'), ('situps', 'Brzuszki'), ('squats', 'Przysiady'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('shoulders', 'Barki')], max_length=20)),
                ('sets', models.PositiveIntegerField()),
                ('repetitions', models.PositiveIntegerField()),
                ('weight', models.FloatField(blank=True, help_text='Waga ciała podczas treningu (kg)', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
