# Generated by Django 5.2.1 on 2025-06-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsessionnew',
            name='temp_field',
            field=models.CharField(blank=True, default='tmp', max_length=10),
        ),
    ]
